#!/bin/sh
# gcc -o ~/src/tracking/trservd $(mysql_config --cflags) -L/usr/lib -lmysqlclient trservpd.c server.c db_manager_mysql.c tracker_report_syst.c common.c
gcc -c trservpd.c server.c db_manager_mysql.c tracker_report_syst.c common.c -I/usr/include/mysql -DBIG_JOINS=1
#-fno-strict-aliasing
# $(mysql_config --cflags)0
gcc trservpd.o server.o db_manager_mysql.o tracker_report_syst.o common.o $(mysql_config --libs) -o trservd
